spring.application.name=ForexCard

server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/sundaram
spring.datasource.username=postgres
<<<<<<< HEAD
#spring.datasource.password=root
spring.datasource.password=@Vikki143
=======
spring.datasource.password=root
#spring.datasource.password=@Vikki143
>>>>>>> 0efe502 (Added 4 entities)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect


